export const BUSINESS_PERMISSIONS = [
  'business.view',
  'business.update',
  'branch.view',
  'branch.create',
  'branch.update',
  'staff.view',
  'staff.invite',
  'staff.update',
  'staff.suspend',
  'product.view',
  'product.create',
  'product.update',
  'product.delete',
  'inventory.view',
  'inventory.adjust',
  'supplier.view',
  'supplier.manage',
  'purchase.view',
  'purchase.create',
  'customer.view',
  'customer.manage',
  'order.view',
  'order.create',
  'order.cancel',
  'order.refund',
  'payment.receive',
  'payment.refund',
  'table.view',
  'table.manage',
  'kot.view',
  'kot.create',
  'kot.update',
  'report.view',
  'settings.manage',
  'subscription.manage',
] as const;

export type PermissionCode = (typeof BUSINESS_PERMISSIONS)[number];

export const ROLE_PERMISSION_MAP: Record<string, readonly PermissionCode[]> = {
  OWNER: BUSINESS_PERMISSIONS,
  MANAGER: BUSINESS_PERMISSIONS.filter((p) => p !== 'subscription.manage'),
  CASHIER: [
    'product.view',
    'customer.view',
    'customer.manage',
    'order.view',
    'order.create',
    'order.cancel',
    'payment.receive',
    'payment.refund',
  ],
  WAITER: ['table.view', 'order.view', 'order.create', 'kot.create', 'customer.view'],
  CHEF: ['kot.view', 'kot.update'],
  KITCHEN_MANAGER: ['kot.view', 'kot.create', 'kot.update', 'table.view'],
  STOCK_MANAGER: [
    'product.view',
    'product.create',
    'product.update',
    'inventory.view',
    'inventory.adjust',
    'supplier.view',
    'supplier.manage',
    'purchase.view',
    'purchase.create',
  ],
  ACCOUNTANT: ['report.view', 'purchase.view', 'payment.receive', 'payment.refund', 'order.refund'],
};
